wandb_version: 1

epochs:
  desc: null
  value: 80
batch_size:
  desc: null
  value: 320
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
max_lenght:
  desc: null
  value: 10
len_dataset:
  desc: null
  value: 150000
split_val:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717025258.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
